version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    depends_on:
      - service

  service:
    build:
      context: ./src/service
      dockerfile: Dockerfile
    container_name: service
    volumes:
      - ./src/service:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
